name: Tests

on: [push, pull_request]

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
